### ISSUE TITLE
Picture In Picture 기능 추가

### ISSUE THREAD

**Issue by x86chi** [x86chi/elearn#2]
## Safari

첫 번째`<video>` 태그를 자동 인식해서 터치바로 실행 가능한 상태이다.

<kbd>⌃⌘P</kbd> 키 트리거를 통해 하단 코드를 실행시키면 괜찮을 것 같다.

`document.querySelector("video#vc-vplay-video1").webkitSetPresentationMode("picture-in-picture")`

## Chrome

베타 `69.0.3483.0` 버전 이상부터 지원 하고 있음
- [Picture-in-Picture Web API](https://wicg.github.io/picture-in-picture/)

**Comment by mu-hun** [comment]
필요 없음
